# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: lighthouse ci check
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: install chrome
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser chromium-browser-l10n

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      - name: run lighthouse check
        run:  npm run lighthouse

      - name: store report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-result.html