# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: lighthouse ci check
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: run lighthouse check
        run:  npm run lighthouse

      - name: store report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-result.html